app = "japanese-sentiment-analyzer-prod"
primary_region = "nrt"

[build]

[env]
  ENVIRONMENT = "production"
  GIT_COMMIT = ""

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8000
    timeout = "10s"
    type = "http"
