app = "japanese-sentiment-analyzer-staging"
primary_region = "nrt"

[build]

[env]
  ENVIRONMENT = "staging"
  GIT_COMMIT = ""
  ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,https://japanese-sentiment-frontend-staging.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8000
    timeout = "10s"
    type = "http"
