name: Deploy Frontend to Fly.io
on:
  push:
    branches: [ main, "devin/1724403880-phase1-initial-setup" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:
    inputs:
      reason:
        description: "Why run?"
        required: false
        default: "manual trigger"

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Deploy to Fly.io
      run: |
        echo "Starting deployment to Fly.io..."
        flyctl deploy --remote-only
      working-directory: ./frontend
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
